name: Python CI

on: [pull_request]

jobs:
  build:
    name: Run tests and check code quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt
    - name: Run pre-commit checks
      run: |
        flake8 . --exclude=venv/
        pylint **/*.py --ignore=venv/
    - name: Run pytest with coverage
      run: pytest --cov=./ --cov-report=term --cov-fail-under=80
